name = "solarized_dark"
display_name = "Solarized Dark"
description = "Popular Solarized color scheme with reduced eye strain"
is_builtin = true

[colors]
background = "#002b36"
text = "#839496"
accent = "#268bd2"
button = "#073642"
button_text = "#eee8d5"
border = "#586e75"
highlight = "#2aa198"
window = "#001e26"
tok_brackets = "#dc322f"
tok_asterisk = "#268bd2"
tok_parentheses = "#cb4b16"
tok_double_brackets = "#859900"
tok_curly_braces = "#d33682"
tok_pipes = "#2aa198"
tok_at_sign = "#b58900"
muted_text = "#586e75"
surface = "#073642"
success_bg = "#324d32"
danger_bg = "#4d2626"
accent_bg = "#073642"
accent_title = "#2aa198"
success_text = "#859900"
error_text = "#dc322f"
warning_text = "#b58900"
tui_primary = "#268bd2"
tui_secondary = "#2aa198"
tui_surface = "#002b36"
tui_panel = "#073642"
tui_warning = "#b58900"
tui_error = "#dc322f"
tui_success = "#859900"
tui_accent = "#6c71c4"
